config/routes.rb
Rails.application.routes.draw do
  get 'sessions/create'

  get 'sessions/destroy'

  devise_for :users,
    controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  get 'welcome/index'

  resources :schedules do
    resources :events  
  end



  resources :yelps

  root 'welcome#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Calendar</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Comfortaa|Fredoka+One" rel="stylesheet">

    <%= javascript_include_tag 'application' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/js/materialize.min.js"></script>

  </head>

  <body>

    <nav>
      <div class="nav-wrapper">
        <%= link_to image_tag("logo-white.png", :class => "logo-img"), root_path, :class => "brand-logo" %></li>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <% if user_signed_in? %>
            <li class="welcome-text">Welcome, <%= current_user.first_name %> <%= current_user.last_name %>!</li>
            <li><%= link_to "New Itinerary", new_schedule_path %></li>
            <li><%= link_to "Your Itineraries", schedules_path %></li>
            <li><%= link_to "Signout", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign In", user_google_oauth2_omniauth_callback_path(provider: :google_oauth2) %></li>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div>
      <%= yield %>
    </div>
  </body>
</html>